services:
  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8112
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=admin1234
    ports:
      - 8112:8112
    volumes:
      - /mnt/qbit/config:/config
    image: lscr.io/linuxserver/qbittorrent:latest


  qbit-port-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      qbittorrent:
        condition: service_started
        restart: true
    environment:
      container_volumes_location: "/mnt"
      node: "192.168.0.7"
      ADMIN_USER: "admin"
      ADMIN_PASS: "admin1234"
      WAIT_TIME: "10s"
      PUID: "1000"
      PGID: "1000"
      TZ: America/New_York
    volumes:
      - /mnt/gluetun:/mnt/gluetun