services:
  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8112
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=admin1234
    ports:
      - 8112:8112
    volumes:
      - /mnt/qbit/config:/config
    image: lscr.io/linuxserver/qbittorrent:latest


  qbit-port-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      qbittorrent:
        condition: service_started
        restart: true
    environment:
      DISCORD_WEBHOOK_URL: your-discord-token-here
      QBITTORRENT_HOST: "http://qbittorrent:8112"
      QBITTORRENT_USERNAME: "admin"
      QBITTORRENT_PASSWORD: "admin1234"
      PORT_FORWARDING: "on"
      PORT_FORWARD_FILE: /mnt/gluetun/forwarded_port
      CHECK_INTERVAL_FORWARDED_PORT: 10s
      PORT_UPDATED_NOTIFICATION: "on"
      CHECK_INTERVAL_TORRENT_MONITORING: 10s
      NEW_DOWNLOAD_NOTIFICATION: "on"
      METADATA_STUCK_NOTIFICATION: "on"
      DOWNLOAD_COMPLETE_NOTIFICATION: "on"
      PUID: "1000"
      PGID: "1000"

    volumes:
      - /mnt/gluetun:/mnt/gluetun
      - /mnt/qbit-monitor:/app/state